package com.sopwithredux;

/**
 * Created by Carl on 01/04/2017.
 */
public enum Event
{
    PLANE_LOST_LIFE, BOMB_DESTROYED_OUTPOST, PLANE_LOST_BOMB, PLANE_LOST_FUEL,
    FUEL_RESTORED,
    MAX_FUEL_RESTORED,
    BOMBS_INCREASED,

    GOTO_MAIN_MENU_SCREEN,
    GOTO_PLAY_SCREEN,
    GOTO_CONTROL_SCREEN,
    GOTO_GAME_OVER_SCREEN
}
